# Generated by Django 6.0.4 on 2026-04-28 06:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Max size 2MB', null=True, upload_to='business_logos/%Y/%m/')),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('website', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#DA291C', max_length=7)),
                ('secondary_color', models.CharField(default='#FFC72C', max_length=7)),
                ('accent_color', models.CharField(default='#FFBD0A', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Info',
                'verbose_name_plural': 'Business Info',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SequenceCounter',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('year', models.IntegerField()),
                ('value', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sequence_counters',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('tiktok', 'TikTok'), ('github', 'GitHub'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('reddit', 'Reddit'), ('medium', 'Medium'), ('twitch', 'Twitch')], max_length=50)),
                ('url', models.URLField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.businessinfo')),
            ],
        ),
    ]
