# Generated by Django 6.0.4 on 2026-04-28 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_detail', to='requests.request'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.vendor'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='current_repair_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repairing_items', to='equipment.vendor'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='original_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_items', to='equipment.vendor'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status', 'assigned_to'], name='equipment_e_status_ee1d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['purchase_date'], name='equipment_e_purchas_dbbcb4_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['tracking_id'], name='equipment_e_trackin_bc9115_idx'),
        ),
    ]
